/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.DKCanBo;
import Model.CanBo;
import Model.DiaBan;
import Model.HeThong;

/**
 *
 * @author thong
 */
public class PnThongTinHeThong extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    private static CanBo userInfo;
    public PnThongTinHeThong(CanBo userInfo) {
        this.userInfo = userInfo;
        initComponents();
        txthoten.setText(userInfo.getHoTen());
        txtcap.setText((userInfo.getCapQL()==1)?"Tỉnh":(userInfo.getCapQL() == 2)? "Huyện" : "Xã");
        DiaBan db = DKCanBo.layDiaBan(userInfo.getCapQL(), userInfo.getDiaBanQL());
        switch (userInfo.getCapQL()) {
            case 1:
                lbhuyen.setVisible(false);
                txthuyen.setVisible(false);
                lbxa.setVisible(false);
                txtxa.setVisible(false);
                txttinh.setText(db.getTinh());
                break;
            case 2:
                lbxa.setVisible(false);
                txtxa.setVisible(false);
                txttinh.setText(db.getTinh());
                txthuyen.setText(db.getHuyen());
                break;
            default:
                txttinh.setText(db.getTinh());
                txthuyen.setText(db.getHuyen());
                txtxa.setText(db.getXa());
        }
        
        txtngheott.setText(""+HeThong.ngheoTT);
        txtnheont.setText(""+HeThong.ngheoNT);
        txtcanngheont.setText(""+HeThong.canNgheoNT);
        txtcanngheott.setText(""+HeThong.canNgheoTT);
        txtnamngheo.setText(""+HeThong.namNgheo);
        cbttrangthai.setSelected(userInfo.isTrangThai());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        txtcap = new javax.swing.JTextField();
        lbhoten = new javax.swing.JLabel();
        lbcnnt = new javax.swing.JLabel();
        lbcap = new javax.swing.JLabel();
        txtcanngheott = new javax.swing.JTextField();
        txtngheott = new javax.swing.JTextField();
        txtnheont = new javax.swing.JTextField();
        txtnamngheo = new javax.swing.JTextField();
        cbttrangthai = new javax.swing.JCheckBox();
        lbnamngheo = new javax.swing.JLabel();
        lbtthethong = new javax.swing.JLabel();
        txthoten = new javax.swing.JTextField();
        lbttnguoidung = new javax.swing.JLabel();
        lbxa = new javax.swing.JLabel();
        lbnnt = new javax.swing.JLabel();
        txtcanngheont = new javax.swing.JTextField();
        lbtinh = new javax.swing.JLabel();
        lbcntt = new javax.swing.JLabel();
        txttinh = new javax.swing.JTextField();
        lbhuyen = new javax.swing.JLabel();
        txtxa = new javax.swing.JTextField();
        lbdiaban = new javax.swing.JLabel();
        txthuyen = new javax.swing.JTextField();
        lbntt = new javax.swing.JLabel();
        lbquyencs = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(900, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtcap.setEditable(false);
        txtcap.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtcap.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jLayeredPane1.add(txtcap, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 81, 180, -1));

        lbhoten.setText("Họ tên");
        jLayeredPane1.add(lbhoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 53, 77, -1));

        lbcnnt.setText("Cận nghèo NT");
        jLayeredPane1.add(lbcnnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, -1, -1));

        lbcap.setText("Cấp quản lý");
        jLayeredPane1.add(lbcap, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, 77, -1));

        txtcanngheott.setEditable(false);
        txtcanngheott.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtcanngheott.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jLayeredPane1.add(txtcanngheott, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 114, -1));

        txtngheott.setEditable(false);
        txtngheott.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtngheott.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jLayeredPane1.add(txtngheott, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 275, 114, -1));

        txtnheont.setEditable(false);
        txtnheont.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtnheont.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jLayeredPane1.add(txtnheont, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 236, 114, -1));

        txtnamngheo.setEditable(false);
        txtnamngheo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtnamngheo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jLayeredPane1.add(txtnamngheo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 114, -1));

        cbttrangthai.setEnabled(false);
        cbttrangthai.setFocusable(false);
        jLayeredPane1.add(cbttrangthai, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 120, -1, -1));

        lbnamngheo.setText("Năm nghèo");
        jLayeredPane1.add(lbnamngheo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, -1, -1));

        lbtthethong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbtthethong.setText("Thông tin hệ thống");
        jLayeredPane1.add(lbtthethong, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 201, -1, -1));

        txthoten.setEditable(false);
        txthoten.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txthoten.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jLayeredPane1.add(txthoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 49, 180, -1));

        lbttnguoidung.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbttnguoidung.setText("Thông tin người dùng");
        jLayeredPane1.add(lbttnguoidung, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        lbxa.setText("Xã");
        jLayeredPane1.add(lbxa, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 51, -1));

        lbnnt.setText("Nghèo NT");
        jLayeredPane1.add(lbnnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        txtcanngheont.setEditable(false);
        txtcanngheont.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtcanngheont.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jLayeredPane1.add(txtcanngheont, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 114, -1));

        lbtinh.setText("Tỉnh");
        jLayeredPane1.add(lbtinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 51, -1));

        lbcntt.setText("Cận Nghèo TT");
        jLayeredPane1.add(lbcntt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));

        txttinh.setEditable(false);
        txttinh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txttinh.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jLayeredPane1.add(txttinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 187, -1));

        lbhuyen.setText("Huyện");
        jLayeredPane1.add(lbhuyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 51, -1));

        txtxa.setEditable(false);
        txtxa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtxa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jLayeredPane1.add(txtxa, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 187, -1));

        lbdiaban.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbdiaban.setText("Địa bàn quản lý");
        jLayeredPane1.add(lbdiaban, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        txthuyen.setEditable(false);
        txthuyen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txthuyen.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jLayeredPane1.add(txthuyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 187, -1));

        lbntt.setText("Nghèo TT");
        jLayeredPane1.add(lbntt, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 275, -1, -1));

        lbquyencs.setText("Quyền chỉnh sửa");
        jLayeredPane1.add(lbquyencs, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, 20));

        add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, 340));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbttrangthai;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lbcap;
    private javax.swing.JLabel lbcnnt;
    private javax.swing.JLabel lbcntt;
    private javax.swing.JLabel lbdiaban;
    private javax.swing.JLabel lbhoten;
    private javax.swing.JLabel lbhuyen;
    private javax.swing.JLabel lbnamngheo;
    private javax.swing.JLabel lbnnt;
    private javax.swing.JLabel lbntt;
    private javax.swing.JLabel lbquyencs;
    private javax.swing.JLabel lbtinh;
    private javax.swing.JLabel lbtthethong;
    private javax.swing.JLabel lbttnguoidung;
    private javax.swing.JLabel lbxa;
    private javax.swing.JTextField txtcanngheont;
    private javax.swing.JTextField txtcanngheott;
    private javax.swing.JTextField txtcap;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txthuyen;
    private javax.swing.JTextField txtnamngheo;
    private javax.swing.JTextField txtngheott;
    private javax.swing.JTextField txtnheont;
    private javax.swing.JTextField txttinh;
    private javax.swing.JTextField txtxa;
    // End of variables declaration//GEN-END:variables
}
