/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Control.DKCanBo;
import Entity.CanBo;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author thong
 */
public class FormCanBo extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private static PnThongTinHeThong pnThongTin;
    private static PnBaoCaoDanhSach pnBaoCao;
    private static PnBaoCaoSoLieu pnBaoCaoSL;
    private static CanBo userInfo;
    private static PnThemHoNgheo pnThemHoNgheo;
    private static PnTimKiemHoNgheo pnTimKiemHn;
    private static PnTimKiemKhauNgheo pnTimKiemKn;

    public FormCanBo(CanBo userInfo) {
        FormCanBo.userInfo = userInfo;
        initComponents();

        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        
        DKCanBo.layThongTinHeThong();
        if (userInfo.getCapQL() == 3)
            userInfo.setIdKhuVuc(DKCanBo.layKhuVuc(userInfo.getDiaBanQL()).id);
        
        for (Component frmChild : pnNoiDung.getComponents()) {
            frmChild.setVisible(false);
        }

        if (pnThongTin == null) {
            pnThongTin = new PnThongTinHeThong(userInfo);
            pnNoiDung.add(pnThongTin);
            pnThongTin.setVisible(true);
            pnNoiDung.validate();
        } else {
            pnThongTin.setVisible(true);
            pnNoiDung.validate();

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        pnNoiDung = new javax.swing.JPanel();
        btthemhn = new javax.swing.JButton();
        bttimkiemhn = new javax.swing.JButton();
        btbaocao = new javax.swing.JButton();
        btbaocaosl = new javax.swing.JButton();
        btquantriht = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuthemhn = new javax.swing.JMenu();
        menuThemHoNgheo = new javax.swing.JMenuItem();
        bttimkn = new javax.swing.JMenu();
        menutimhn = new javax.swing.JMenuItem();
        menutimkn = new javax.swing.JMenuItem();
        menubcds = new javax.swing.JMenu();
        menubaocaodanhsach = new javax.swing.JMenuItem();
        menubcsl = new javax.swing.JMenuItem();
        menuttht = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phần mềm quản lý hộ nghèo - Nhóm 2");
        setBackground(new java.awt.Color(102, 102, 102));
        setForeground(new java.awt.Color(153, 153, 153));
        setMaximumSize(new java.awt.Dimension(1920, 1280));
        setMinimumSize(new java.awt.Dimension(1044, 668));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnNoiDung.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        pnNoiDung.setMinimumSize(new java.awt.Dimension(893, 604));
        pnNoiDung.setPreferredSize(new java.awt.Dimension(900, 600));
        pnNoiDung.setLayout(new javax.swing.BoxLayout(pnNoiDung, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(pnNoiDung, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 41, 1137, 631));

        btthemhn.setText("Thêm hộ nghèo");
        btthemhn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btthemhnActionPerformed(evt);
            }
        });
        getContentPane().add(btthemhn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 41, 123, -1));

        bttimkiemhn.setText("Tìm kiếm");
        bttimkiemhn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttimkiemhnActionPerformed(evt);
            }
        });
        getContentPane().add(bttimkiemhn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 82, 123, -1));

        btbaocao.setText("Báo cáo");
        btbaocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbaocaoActionPerformed(evt);
            }
        });
        getContentPane().add(btbaocao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 123, 123, -1));

        btbaocaosl.setText("Báo cáo số liệu");
        btbaocaosl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbaocaoslActionPerformed(evt);
            }
        });
        getContentPane().add(btbaocaosl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 164, 123, -1));

        btquantriht.setText("Quản trị hệ thống");
        btquantriht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btquantrihtActionPerformed(evt);
            }
        });
        getContentPane().add(btquantriht, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 205, 123, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Nhóm 2");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 8, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setText("Phần mềm quản lý hộ nghèo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 8, 200, -1));

        menuthemhn.setText("Quản lý");

        menuThemHoNgheo.setText("Thêm hộ nghèo");
        menuThemHoNgheo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThemHoNgheoActionPerformed(evt);
            }
        });
        menuthemhn.add(menuThemHoNgheo);

        jMenuBar1.add(menuthemhn);

        bttimkn.setText("Tìm kiếm");

        menutimhn.setText("Tìm kiếm hộ nghèo");
        menutimhn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menutimhnActionPerformed(evt);
            }
        });
        bttimkn.add(menutimhn);

        menutimkn.setText("Tìm kiếm khẩu nghèo");
        menutimkn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menutimknActionPerformed(evt);
            }
        });
        bttimkn.add(menutimkn);

        jMenuBar1.add(bttimkn);

        menubcds.setText("Báo cáo");

        menubaocaodanhsach.setText("Báo cáo danh sách");
        menubaocaodanhsach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubaocaodanhsachActionPerformed(evt);
            }
        });
        menubcds.add(menubaocaodanhsach);

        menubcsl.setText("Báo cáo số liệu");
        menubcsl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubcslActionPerformed(evt);
            }
        });
        menubcds.add(menubcsl);

        jMenuBar1.add(menubcds);

        menuttht.setText("Quản trị");

        jMenuItem1.setText("Thông tin hệ thống");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuttht.add(jMenuItem1);

        jMenuBar1.add(menuttht);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuThemHoNgheoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThemHoNgheoActionPerformed
        // TODO add your handling code here:

        if (userInfo.getCapQL() < 3 || !userInfo.isTrangThai()) {
            JOptionPane.showMessageDialog(this, "Bạn không có quyền thêm hộ nghèo");
            return;
        }
        for (Component frmChild : pnNoiDung.getComponents()) {
            frmChild.setVisible(false);
        }

        if (pnThemHoNgheo == null) {
            pnThemHoNgheo = new PnThemHoNgheo(userInfo);
            pnNoiDung.add(pnThemHoNgheo);
            pnThemHoNgheo.setVisible(true);
            pnNoiDung.validate();
        } else {
            pnThemHoNgheo.setVisible(true);
            pnNoiDung.validate();
        }
    }//GEN-LAST:event_menuThemHoNgheoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        for (Component frmChild : pnNoiDung.getComponents()) {
            frmChild.setVisible(false);
        }

        if (pnThongTin == null) {
            pnThongTin = new PnThongTinHeThong(userInfo);
            pnNoiDung.add(pnThongTin);
            pnThongTin.setVisible(true);
            pnNoiDung.validate();
        } else {
            pnThongTin.setVisible(true);
            pnNoiDung.validate();

        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menutimhnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menutimhnActionPerformed
        // TODO add your handling code here:
        for (Component frmChild : pnNoiDung.getComponents()) {
            frmChild.setVisible(false);
        }
        
        if (pnTimKiemHn == null) {
            pnTimKiemHn = new PnTimKiemHoNgheo(userInfo);
            pnNoiDung.add(pnTimKiemHn);
            pnTimKiemHn.setVisible(true);
            pnNoiDung.validate();
        } else {
            pnTimKiemHn.setVisible(true);
            pnNoiDung.validate();
        } 
    }//GEN-LAST:event_menutimhnActionPerformed

    private void menubaocaodanhsachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubaocaodanhsachActionPerformed
        // TODO add your handling code here:
          for (Component frmChild : pnNoiDung.getComponents()) {
            frmChild.setVisible(false);
        }
        
        if (pnBaoCao == null) {
            pnBaoCao = new PnBaoCaoDanhSach(userInfo);
            pnNoiDung.add(pnBaoCao);
            pnBaoCao.setVisible(true);
            pnNoiDung.validate();
        } else {
            pnBaoCao.setVisible(true);
            pnNoiDung.validate();
        } 
    }//GEN-LAST:event_menubaocaodanhsachActionPerformed

    private void bttimkiemhnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttimkiemhnActionPerformed
        // TODO add your handling code here:
           for (Component frmChild : pnNoiDung.getComponents()) {
            frmChild.setVisible(false);
        }
        
        if (pnTimKiemHn == null) {
            pnTimKiemHn = new PnTimKiemHoNgheo(userInfo);
            pnNoiDung.add(pnTimKiemHn);
            pnTimKiemHn.setVisible(true);
            pnNoiDung.validate();
        } else {
            pnTimKiemHn.setVisible(true);
            pnNoiDung.validate();
        } 
    }//GEN-LAST:event_bttimkiemhnActionPerformed

    private void menutimknActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menutimknActionPerformed
        // TODO add your handling code here:
          for (Component frmChild : pnNoiDung.getComponents()) {
            frmChild.setVisible(false);
        }

        if (pnTimKiemKn == null) {
            pnTimKiemKn = new PnTimKiemKhauNgheo(userInfo);
            pnNoiDung.add(pnTimKiemKn);
            pnTimKiemKn.setVisible(true);
            pnNoiDung.validate();
        } else {
            pnTimKiemKn.setVisible(true);
            pnNoiDung.validate();
        }
    }//GEN-LAST:event_menutimknActionPerformed

    private void btthemhnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthemhnActionPerformed
        // TODO add your handling code here:
         if (userInfo.getCapQL() < 3 || !userInfo.isTrangThai()) {
            JOptionPane.showMessageDialog(this, "Bạn không có quyền thêm hộ nghèo");
            return;
        }
        for (Component frmChild : pnNoiDung.getComponents()) {
            frmChild.setVisible(false);
        }

        if (pnThemHoNgheo == null) {
            pnThemHoNgheo = new PnThemHoNgheo(userInfo);
            pnNoiDung.add(pnThemHoNgheo);
            pnThemHoNgheo.setVisible(true);
            pnNoiDung.validate();
        } else {
            pnThemHoNgheo.setVisible(true);
            pnNoiDung.validate();
        }
    }//GEN-LAST:event_btthemhnActionPerformed

    private void btbaocaoslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbaocaoslActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btbaocaoslActionPerformed

    private void btquantrihtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btquantrihtActionPerformed
        // TODO add your handling code here:
          for (Component frmChild : pnNoiDung.getComponents()) {
            frmChild.setVisible(false);
        }

        if (pnThongTin == null) {
            pnThongTin = new PnThongTinHeThong(userInfo);
            pnNoiDung.add(pnThongTin);
            pnThongTin.setVisible(true);
            pnNoiDung.validate();
        } else {
            pnThongTin.setVisible(true);
            pnNoiDung.validate();

        }
    }//GEN-LAST:event_btquantrihtActionPerformed

    private void btbaocaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbaocaoActionPerformed
        // TODO add your handling code here:
            for (Component frmChild : pnNoiDung.getComponents()) {
            frmChild.setVisible(false);
        }
        
        if (pnBaoCao == null) {
            pnBaoCao = new PnBaoCaoDanhSach(userInfo);
            pnNoiDung.add(pnBaoCao);
            pnBaoCao.setVisible(true);
            pnNoiDung.validate();
        } else {
            pnBaoCao.setVisible(true);
            pnNoiDung.validate();
        } 
    }//GEN-LAST:event_btbaocaoActionPerformed

    private void menubcslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubcslActionPerformed
        // TODO add your handling code here:
          for (Component frmChild : pnNoiDung.getComponents()) {
            frmChild.setVisible(false);
        }
        
        if (pnBaoCaoSL == null) {
            pnBaoCaoSL = new PnBaoCaoSoLieu(userInfo);
            pnNoiDung.add(pnBaoCaoSL);
            pnBaoCaoSL.setVisible(true);
            pnNoiDung.validate();
        } else {
            pnBaoCaoSL.setVisible(true);
            pnNoiDung.validate();
        } 
    }//GEN-LAST:event_menubcslActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCanBo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCanBo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCanBo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCanBo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCanBo(userInfo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbaocao;
    private javax.swing.JButton btbaocaosl;
    private javax.swing.JButton btquantriht;
    private javax.swing.JButton btthemhn;
    private javax.swing.JButton bttimkiemhn;
    private javax.swing.JMenu bttimkn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem menuThemHoNgheo;
    private javax.swing.JMenuItem menubaocaodanhsach;
    private javax.swing.JMenu menubcds;
    private javax.swing.JMenuItem menubcsl;
    private javax.swing.JMenu menuthemhn;
    private javax.swing.JMenuItem menutimhn;
    private javax.swing.JMenuItem menutimkn;
    private javax.swing.JMenu menuttht;
    private javax.swing.JPanel pnNoiDung;
    // End of variables declaration//GEN-END:variables
}
