/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Entity.DanhMuc;
import Entity.KhauNgheo;
import Entity.CanBo;
import Entity.HeThong;
import Entity.DiaBan;
import Control.DKCanBo;
import Entity.HoNgheo;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Vector;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thong
 */
public final class PnThemHoNgheo extends javax.swing.JPanel {

    /**
     * Creates new form PnThemHoNgheo
     */
    private static CanBo userInfo;
    private static JFrame father;
    private static HoNgheo hoNgheo;
    private static final ArrayList<KhauNgheo> listkn = new ArrayList<>();
    private static boolean themMoi = true;

    public PnThemHoNgheo(CanBo userInfo) {
        this.userInfo = userInfo;

        initComponents();
        loadComBox();
        loadDiaBan();
        xemDanhSachKN();
        
        txtnamngheo.setText("" + HeThong.namNgheo);
        btchinhsua.setEnabled(false);

        if (userInfo.isTrangThai() == false) {
            btchinhsua.setVisible(false);
            btthemhn.setVisible(false);
            btthemkn.setVisible(false);
            JOptionPane.showMessageDialog(null, "Bạn hiện không có quyền thêm, liên hệ cấp quản trị cao hơn để biết thêm thông tin", "Thông báo", 2);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxdantockn = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cbxgioitinh = new javax.swing.JComboBox();
        cbxquanhe = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        txthotenkn = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cbxnhao = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        cbxnguyennhan = new javax.swing.JComboBox();
        cbxnuoc = new javax.swing.JComboBox();
        cbDaCapThe = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        txtthunhap = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtnamngheo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cbxkhuvuc = new javax.swing.JComboBox();
        cbxphanloai = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        cbxdantocch = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtxa = new javax.swing.JTextField();
        txtxom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txthuyen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txthotench = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        txtnamsinhkn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtmahn = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btchinhsua = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btthemhn = new javax.swing.JButton();
        btthemkn = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        cbxnghenghiep = new javax.swing.JComboBox();
        cbxdoituong = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbdanhsachkn = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add(cbxdantockn, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 305, 125, -1));

        jLabel22.setText("Nghề nghiệp");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 308, 73, -1));

        jLabel20.setText("Năm Sinh");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(884, 270, -1, -1));

        jLabel21.setText("Dân tộc");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 308, 81, -1));

        jLabel19.setText("Giới tính");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(679, 270, 58, -1));

        cbxgioitinh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1.Nam", "2.Nữ" }));
        add(cbxgioitinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(747, 267, 71, -1));

        add(cbxquanhe, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 267, 139, -1));

        jLabel18.setText("Quan hệ với chủ hộ");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 270, 109, -1));
        add(txthotenkn, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 267, 125, -1));

        jLabel17.setText("Họ tên");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 81, -1));

        jLabel16.setBackground(new java.awt.Color(0, 0, 153));
        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel16.setText("Danh sách khẩu nghèo");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 226, 1071, -1));

        jLabel14.setText("Nhà ở");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 128, 81, -1));

        add(cbxnhao, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 125, 128, -1));

        jLabel15.setText("Nguyên nhân nghèo");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 128, -1, -1));

        add(cbxnguyennhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 125, 220, -1));

        add(cbxnuoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 125, 154, -1));

        cbDaCapThe.setText("Đã cấp thẻ");
        add(cbDaCapThe, new org.netbeans.lib.awtextra.AbsoluteConstraints(827, 178, 100, -1));

        jLabel13.setText("Nước sạch");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 128, 78, -1));

        txtthunhap.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtthunhap.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtthunhapFocusLost(evt);
            }
        });
        add(txtthunhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 87, 100, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Thu nhập");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 90, 97, -1));

        txtnamngheo.setEditable(false);
        txtnamngheo.setBackground(new java.awt.Color(204, 204, 204));
        txtnamngheo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtnamngheo.setEnabled(false);
        txtnamngheo.setFocusable(false);
        add(txtnamngheo, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 179, 128, -1));

        jLabel12.setText("Năm nghèo");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 182, 81, -1));

        cbxkhuvuc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cbxkhuvuc.setEnabled(false);
        cbxkhuvuc.setFocusable(false);
        cbxkhuvuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxkhuvucActionPerformed(evt);
            }
        });
        add(cbxkhuvuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 87, 128, -1));

        cbxphanloai.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cbxphanloai.setEnabled(false);
        cbxphanloai.setFocusable(false);
        add(cbxphanloai, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 90, 139, -1));

        jLabel9.setText("Phân Loại");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 90, 58, -1));

        add(cbxdantocch, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 87, 154, -1));

        jLabel8.setText("Dân Tộc");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 90, 78, -1));

        jLabel7.setText("Huyện");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 50, 52, -1));

        txtxa.setEditable(false);
        txtxa.setBackground(new java.awt.Color(204, 204, 204));
        txtxa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtxa.setEnabled(false);
        txtxa.setFocusable(false);
        add(txtxa, new org.netbeans.lib.awtextra.AbsoluteConstraints(733, 49, 108, -1));
        add(txtxom, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 49, 63, -1));

        jLabel3.setText("Xã");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(697, 52, 32, -1));

        txthuyen.setEditable(false);
        txthuyen.setBackground(new java.awt.Color(204, 204, 204));
        txthuyen.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txthuyen.setEnabled(false);
        txthuyen.setFocusable(false);
        add(txthuyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 50, 139, -1));

        jLabel6.setText("Khu Vực");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 81, -1));

        txthotench.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txthotenchFocusLost(evt);
            }
        });
        add(txthotench, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 49, 154, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Hủy");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 560, 103, -1));
        add(txtnamsinhkn, new org.netbeans.lib.awtextra.AbsoluteConstraints(946, 267, 100, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Tên chủ hộ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 52, 78, -1));

        jLabel24.setText("000 VNĐ/Người/Tháng");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 110, -1));

        txtmahn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtmahnFocusLost(evt);
            }
        });
        add(txtmahn, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 49, 128, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Thêm hộ nghèo");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 161, 27));

        jLabel5.setText("Thôn/Xóm");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 52, 97, -1));

        btchinhsua.setText("Chỉnh sửa");
        btchinhsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btchinhsuaActionPerformed(evt);
            }
        });
        add(btchinhsua, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 343, 113, -1));

        jButton3.setText("Xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 343, 97, -1));

        btthemhn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btthemhn.setText("Thêm");
        btthemhn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btthemhnActionPerformed(evt);
            }
        });
        add(btthemhn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 562, 100, -1));

        btthemkn.setText("Thêm khẩu nghèo");
        btthemkn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btthemknActionPerformed(evt);
            }
        });
        add(btthemkn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 343, 129, -1));

        jLabel23.setText("Đối tượng chính sách");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(679, 308, 126, -1));

        add(cbxnghenghiep, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 305, 139, -1));

        add(cbxdoituong, new org.netbeans.lib.awtextra.AbsoluteConstraints(823, 305, 220, -1));

        tbdanhsachkn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbdanhsachkn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdanhsachknMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbdanhsachkn);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 384, 1090, 167));

        jLabel2.setText("Mã hộ nghèo");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, 81, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtthunhapFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtthunhapFocusLost
        // TODO add your handling code here:
        int tn;
        if (txtthunhap.getText().equals(""))
            return;
        try {
            tn = Integer.parseInt(txtthunhap.getText()) * 1000;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Thu nhập phải là số nguyên theo đơn vị VNĐ");
            txtthunhap.setText("");
            return;
        }

        if (tn < 0) {
            JOptionPane.showMessageDialog(this, "Thu nhập không hợp lệ");
            txtthunhap.setText("");
            return;
        }

        if (userInfo.getIdKhuVuc() == 1) {
            if (tn > HeThong.canNgheoNT) {
                JOptionPane.showMessageDialog(this, "Thu nhập không nằm trong đối tượng hộ nghèo hoặc cận nghèo");
                txtthunhap.setText("");
            } else if (tn <= HeThong.ngheoNT) {
                cbxphanloai.setSelectedIndex(0); //Ngheo NT
            } else {
                cbxphanloai.setSelectedIndex(1); //Can Ngheo NT
            }
        } else if (tn > HeThong.canNgheoTT) {
            JOptionPane.showMessageDialog(this, "Thu nhập không nằm trong đối tượng hộ nghèo hoặc cận nghèo");
            txtthunhap.setText("");
        } else if (tn <= HeThong.ngheoTT) {
            cbxphanloai.setSelectedIndex(2);
        } else {
            cbxphanloai.setSelectedIndex(3);
        }
    }//GEN-LAST:event_txtthunhapFocusLost

    private void cbxkhuvucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxkhuvucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxkhuvucActionPerformed

    private void txthotenchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txthotenchFocusLost
        // TODO add your handling code here:
        txthotenkn.setText(txthotench.getText());
        cbxquanhe.setSelectedIndex(0);
    }//GEN-LAST:event_txthotenchFocusLost

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        xoaHienThi();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtmahnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmahnFocusLost
        // TODO add your handling code here:
        if (txtmahn.getText().equals("")) {
            themMoi = false;
            btthemhn.setText("Thêm Mới");
            //lbkieuthem.setText("Thêm hộ nghèo mới");
        }

        try {
            int idHoNgheo = Integer.parseInt(txtmahn.getText());
            HoNgheo hoNgheo = DKCanBo.layThongTinHN(idHoNgheo);
            if (hoNgheo == null) {
                JOptionPane.showMessageDialog(this, "Mã hộ nghèo không tồn tại", "Thông báo lỗi", 2);
                xoaHienThi();
            }
            hienThiHoNgheo(hoNgheo, idHoNgheo);
            
            themMoi = false;
            btthemhn.setText("Thêm Cũ");
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_txtmahnFocusLost

    private void btchinhsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btchinhsuaActionPerformed
        // TODO add your handling code here:
        if (txthotenkn.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập tên khẩu nghèo");
            return;
        }
        if (txtnamsinhkn.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập năm sinh khẩu nghèo");
            return;
        }

        try {
            if (Integer.parseInt(txtnamsinhkn.getText()) < HeThong.namNgheo - 130) {
                JOptionPane.showMessageDialog(this, "Năm sinh khẩu nghèo không hợp lệ");
                return;
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Năm sinh phải là số");
            txtnamsinhkn.setText("");
            return;
        }

        KhauNgheo khauNgheo = new KhauNgheo(txthotenkn.getText(), getIDInt(cbxquanhe), (getIDInt(cbxgioitinh) == 1), getIDInt(cbxdantocch),
                getIDInt(cbxnghenghiep), getIDInt(cbxdoituong), Integer.parseInt(txtnamsinhkn.getText()));

        int index = tbdanhsachkn.getSelectedRow();
        listkn.set(index, khauNgheo);
        xemDanhSachKN();
        tbdanhsachkn.clearSelection();
        btchinhsua.setEnabled(false);
    }//GEN-LAST:event_btchinhsuaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int index = tbdanhsachkn.getSelectedRow();
        listkn.remove(index);
        xemDanhSachKN();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btthemhnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthemhnActionPerformed
        // TODO add your handling code here:
        try {
            if (txthotench.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Chưa nhập họ tên chủ hộ");
                return;
            }

            if (txtxom.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Chưa nhập xóm");
                return;
            }

            if (txtthunhap.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Chưa nhập mức thu nhập");
                return;
            }

            HoNgheo hoNgheo = new HoNgheo(txthotench.getText(), txtxom.getText(), userInfo.getDiaBanQL(), getIDInt(cbxdantocch), getIDInt(cbxphanloai), Integer.parseInt(txtthunhap.getText()) * 1000, getIDInt(cbxnuoc), getIDInt(cbxnguyennhan), cbDaCapThe.isSelected() ? true : false, getIDInt(cbxnhao));
            for (KhauNgheo kn : listkn) {
                hoNgheo.themKN(kn);
            }

            if (themMoi) {
                int idHoNgheo = DKCanBo.themHoNgheo(hoNgheo);
                if (idHoNgheo >= 0) {
                    if (DKCanBo.themVaoDanhSachHN(idHoNgheo, HeThong.namNgheo)) {
                        JOptionPane.showMessageDialog(this, "Đã thêm thành công hộ nghèo, mã hộ nghèo là:  " + idHoNgheo, "Thêm hộ nghèo thành công", 1);
                        txtmahn.setText("" + idHoNgheo);
                        listkn.clear();
                    }
                }
            } else {
                int idHoNgheo = Integer.parseInt(txtmahn.getText());
                if (!DKCanBo.themVaoDanhSachHN(idHoNgheo, HeThong.namNgheo)) {
                    JOptionPane.showMessageDialog(this, "Hộ nghèo đã được thêm lại từ trước.", "Thất bại", 1);
                } else if (DKCanBo.suaHoNgheo(hoNgheo, idHoNgheo)) {
                    JOptionPane.showMessageDialog(this, "Đã thêm hộ nghèo cũ thành công", "Thành công", 1);
                } else {
                    DKCanBo.xoaKhoiDanhSachHN(idHoNgheo, HeThong.namNgheo);
                    JOptionPane.showMessageDialog(this, "Kiểm tra lại thông tin hộ nghèo", "Thất bại", 1);
                }

            }

        } catch (HeadlessException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Đã có lỗi xảy ra, không thể thêm hộ nghèo", "Thông báo lỗi", 2);
        }
    }//GEN-LAST:event_btthemhnActionPerformed

    private void btthemknActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthemknActionPerformed
        // TODO add your handling code here:
        if (txthotenkn.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập tên khẩu nghèo");
            return;
        }
        if (txtnamsinhkn.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập năm sinh khẩu nghèo");
            return;
        }

        try {
            if (Integer.parseInt(txtnamsinhkn.getText()) < HeThong.namNgheo - 130) {
                JOptionPane.showMessageDialog(this, "Năm sinh khẩu nghèo không hợp lệ");
                return;
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Năm sinh phải là số");
            txtnamsinhkn.setText("");
            return;
        }

        KhauNgheo khauNgheo = new KhauNgheo(txthotenkn.getText(), getIDInt(cbxquanhe), (getIDInt(cbxgioitinh) == 1), getIDInt(cbxdantocch),
                getIDInt(cbxnghenghiep), getIDInt(cbxdoituong), Integer.parseInt(txtnamsinhkn.getText()));
        listkn.add(khauNgheo);
        xemDanhSachKN();
    }//GEN-LAST:event_btthemknActionPerformed

    private void tbdanhsachknMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdanhsachknMouseClicked
        // TODO add your handling code here:
        int index = tbdanhsachkn.getSelectedRow();
        KhauNgheo khauNgheo = listkn.get(index);
        hienThiKhauNgheo(khauNgheo);
        btchinhsua.setEnabled(true);
    }//GEN-LAST:event_tbdanhsachknMouseClicked

    private void hienThiKhauNgheo(KhauNgheo khauNgheo) {
        txthotenkn.setText(khauNgheo.getHoTen());
        cbxquanhe.setSelectedIndex(khauNgheo.getIdQuanHeCH() - 1);
        cbxgioitinh.setSelectedIndex(khauNgheo.isGioiTinh() ? 0 : 1);
        txtnamsinhkn.setText("" + khauNgheo.getNamSinh());
        cbxdantockn.setSelectedIndex(khauNgheo.getIdDanToc() - 1);
        cbxnghenghiep.setSelectedIndex(khauNgheo.getIdNgheNghiep() - 1);
        cbxdoituong.setSelectedIndex(khauNgheo.getIdDoiTuong() - 1);
    }

    private void xoaHienThi() {
        txthotenkn.setText("");
        cbxquanhe.setSelectedIndex(0);
        cbxgioitinh.setSelectedIndex(0);
        txtnamsinhkn.setText("");
        cbxdantockn.setSelectedIndex(0);
        cbxnghenghiep.setSelectedIndex(0);
        cbxdoituong.setSelectedIndex(0);

        txtmahn.setText("");
        txthotench.setText("");
        txtxom.setText("");
        txtxa.setText("");
        txthuyen.setText("");
        cbxkhuvuc.setSelectedIndex(0);
        cbxdantocch.setSelectedIndex(0);
        txtthunhap.setText("");
        cbxphanloai.setSelectedIndex(0);
        cbxnhao.setSelectedIndex(0);
        cbxnuoc.setSelectedIndex(0);
        cbxnguyennhan.setSelectedIndex(0);
        txtnamngheo.setText("");
        cbDaCapThe.setSelected(false);

        listkn.clear();
        xemDanhSachKN();
    }

    public void hienThiHoNgheo(HoNgheo hoNgheo, int idHoNgheo) {
        if (idHoNgheo != 0) {
            txtmahn.setText("" + idHoNgheo);
        }
        txthotench.setText(hoNgheo.getTenCH());
        txtxom.setText(hoNgheo.getXom());
        DiaBan db = DKCanBo.layDiaBan(3, hoNgheo.getIdXa());
        txtxa.setText(db.getXa());
        txthuyen.setText(db.getHuyen());
        cbxkhuvuc.setSelectedIndex(userInfo.getIdKhuVuc() - 1);
        cbxdantocch.setSelectedIndex(hoNgheo.getIdDanToc() - 1);
        txtthunhap.setText("" + hoNgheo.getThuNhapTB() / 1000);
        cbxphanloai.setSelectedIndex(hoNgheo.getIdPhanLoai() - 1);
        cbxnhao.setSelectedIndex(hoNgheo.getIdNhaO() - 1);
        cbxnuoc.setSelectedIndex(hoNgheo.getIdNuoc() - 1);
        cbxnguyennhan.setSelectedIndex(hoNgheo.getIdNguyenNhan() - 1);
        txtnamngheo.setText("" + HeThong.namNgheo);
        cbDaCapThe.setSelected(hoNgheo.isTrangThai());

        listkn.clear();
        listkn.addAll(hoNgheo.getListKN());
        xemDanhSachKN();
    }

    public void xemDanhSachKN() {
        Vector cols = new Vector();
        cols.addElement("Họ Tên");
        cols.addElement("Giới Tính");
        cols.addElement("Năm Sinh");
        cols.addElement("QH Với Chủ Hộ");
        cols.addElement("Đối tượng");
        cols.addElement("Nghề Nghiệp");

        Vector data = new Vector();
        for (KhauNgheo i : listkn) {
            Vector user = new Vector();
            user.addElement(i.getHoTen());
            user.addElement(i.isGioiTinh() ? "Nam" : "Nữ");
            user.addElement("" + i.getNamSinh());

            //-1 vi danh muc bat dau tu 0
            user.addElement(HeThong.dmQuanHe.get(i.getIdQuanHeCH() - 1).ten);
            user.addElement(HeThong.dmDoiTuong.get(i.getIdDoiTuong() - 1).ten);
            user.addElement(HeThong.dmNgheNghiep.get(i.getIdNgheNghiep() - 1).ten);

            data.add(user);
        }

        tbdanhsachkn.setModel(new MyTableModel(data, cols));
    }

    private String getIDStr(JComboBox cbx) {
        return cbx.getSelectedItem().toString().split("\\.")[0];
    }

    private int getIDInt(JComboBox cbx) {
        return Integer.parseInt(cbx.getSelectedItem().toString().split("\\.")[0]);
    }

    public void loadComBox() {
        for (DanhMuc i : HeThong.dmDanToc) {
            cbxdantocch.addItem(i.id + "." + i.ten);
        }
        for (DanhMuc i : HeThong.dmDoiTuong) {
            cbxdoituong.addItem(i.id + "." + i.ten);
        }
        for (DanhMuc i : HeThong.dmKhuVuc) {
            cbxkhuvuc.addItem(i.id + "." + i.ten);
        }
        for (DanhMuc i : HeThong.dmNgheNghiep) {
            cbxnghenghiep.addItem(i.id + "." + i.ten);
        }
        for (DanhMuc i : HeThong.dmNguyenNhan) {
            cbxnguyennhan.addItem(i.id + "." + i.ten);
        }
        for (DanhMuc i : HeThong.dmNhaO) {
            cbxnhao.addItem(i.id + "." + i.ten);
        }
        for (DanhMuc i : HeThong.dmNuoc) {
            cbxnuoc.addItem(i.id + "." + i.ten);
        }
        for (DanhMuc i : HeThong.dmPhanLoai) {
            cbxphanloai.addItem(i.id + "." + i.ten);
        }
        for (DanhMuc i : HeThong.dmQuanHe) {
            cbxquanhe.addItem(i.id + "." + i.ten);
        }
        for (DanhMuc i : HeThong.dmDanToc) {
            cbxdantockn.addItem(i.id + "." + i.ten);
        }
    }

    public void loadDiaBan() {
        DiaBan db = DKCanBo.layDiaBan(userInfo.getCapQL(), userInfo.getDiaBanQL());
        txthuyen.setText(db.getHuyen());
        txtxa.setText(db.getXa());
        cbxkhuvuc.setSelectedIndex(userInfo.getIdKhuVuc() - 1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btchinhsua;
    private javax.swing.JButton btthemhn;
    private javax.swing.JButton btthemkn;
    private javax.swing.JCheckBox cbDaCapThe;
    private javax.swing.JComboBox cbxdantocch;
    private javax.swing.JComboBox cbxdantockn;
    private javax.swing.JComboBox cbxdoituong;
    private javax.swing.JComboBox cbxgioitinh;
    private javax.swing.JComboBox cbxkhuvuc;
    private javax.swing.JComboBox cbxnghenghiep;
    private javax.swing.JComboBox cbxnguyennhan;
    private javax.swing.JComboBox cbxnhao;
    private javax.swing.JComboBox cbxnuoc;
    private javax.swing.JComboBox cbxphanloai;
    private javax.swing.JComboBox cbxquanhe;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbdanhsachkn;
    private javax.swing.JTextField txthotench;
    private javax.swing.JTextField txthotenkn;
    private javax.swing.JTextField txthuyen;
    private javax.swing.JTextField txtmahn;
    private javax.swing.JTextField txtnamngheo;
    private javax.swing.JTextField txtnamsinhkn;
    private javax.swing.JTextField txtthunhap;
    private javax.swing.JTextField txtxa;
    private javax.swing.JTextField txtxom;
    // End of variables declaration//GEN-END:variables
}

class MyTableModel extends DefaultTableModel {

    @Override
    public boolean isCellEditable(int row, int column) {
        return false;
    }

    public MyTableModel(Vector data, Vector cols) {
        super(data, cols);
    }
}
