/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Control.DKCanBo;
import Entity.CanBo;
import Entity.DiaBan;
import Entity.HeThong;

/**
 *
 * @author thong
 */
public class PnThongTinHeThong extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    private static CanBo userInfo;
    public PnThongTinHeThong(CanBo userInfo) {
        this.userInfo = userInfo;
        initComponents();
        txthoten.setText(userInfo.getHoTen());
        txtcap.setText((userInfo.getCapQL()==1)?"Tỉnh":(userInfo.getCapQL() == 2)? "Huyện" : "Xã");
        DiaBan db = DKCanBo.layDiaBan(userInfo.getCapQL(), userInfo.getDiaBanQL());
        switch (userInfo.getCapQL()) {
            case 1:
                lbhuyen.setVisible(false);
                txthuyen.setVisible(false);
                lbxa.setVisible(false);
                txtxa.setVisible(false);
                txttinh.setText(db.getTinh());
                break;
            case 2:
                lbxa.setVisible(false);
                txtxa.setVisible(false);
                txttinh.setText(db.getTinh());
                txthuyen.setText(db.getHuyen());
                break;
            default:
                txttinh.setText(db.getTinh());
                txthuyen.setText(db.getHuyen());
                txtxa.setText(db.getXa());
        }
        
        txtngheott.setText(""+HeThong.ngheoTT);
        txtnheont.setText(""+HeThong.ngheoNT);
        txtcanngheont.setText(""+HeThong.canNgheoNT);
        txtcanngheott.setText(""+HeThong.canNgheoTT);
        txtnamngheo.setText(""+HeThong.namNgheo);
        cbttrangthai.setSelected(userInfo.isTrangThai());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        txtcap = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtcanngheott = new javax.swing.JTextField();
        txtngheott = new javax.swing.JTextField();
        txtnheont = new javax.swing.JTextField();
        txtnamngheo = new javax.swing.JTextField();
        cbttrangthai = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txthoten = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbxa = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtcanngheont = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txttinh = new javax.swing.JTextField();
        lbhuyen = new javax.swing.JLabel();
        txtxa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txthuyen = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(900, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtcap.setEditable(false);
        txtcap.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtcap.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jLayeredPane1.add(txtcap, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 81, 180, -1));

        jLabel2.setText("Họ tên");
        jLayeredPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 53, 77, -1));

        jLabel12.setText("Cận nghèo NT");
        jLayeredPane1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, -1, -1));

        jLabel3.setText("Cấp quản lý");
        jLayeredPane1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, 77, -1));

        txtcanngheott.setEditable(false);
        txtcanngheott.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtcanngheott.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jLayeredPane1.add(txtcanngheott, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 114, -1));

        txtngheott.setEditable(false);
        txtngheott.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtngheott.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jLayeredPane1.add(txtngheott, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 275, 114, -1));

        txtnheont.setEditable(false);
        txtnheont.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtnheont.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jLayeredPane1.add(txtnheont, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 236, 114, -1));

        txtnamngheo.setEditable(false);
        txtnamngheo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtnamngheo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jLayeredPane1.add(txtnamngheo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 114, -1));

        cbttrangthai.setEnabled(false);
        cbttrangthai.setFocusable(false);
        jLayeredPane1.add(cbttrangthai, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 120, -1, -1));

        jLabel9.setText("Năm nghèo");
        jLayeredPane1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Thông tin hệ thống");
        jLayeredPane1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 201, -1, -1));

        txthoten.setEditable(false);
        txthoten.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txthoten.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jLayeredPane1.add(txthoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 49, 180, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Thông tin người dùng");
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        lbxa.setText("Xã");
        jLayeredPane1.add(lbxa, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 51, -1));

        jLabel10.setText("Nghèo NT");
        jLayeredPane1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        txtcanngheont.setEditable(false);
        txtcanngheont.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtcanngheont.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jLayeredPane1.add(txtcanngheont, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 114, -1));

        jLabel7.setText("Tỉnh");
        jLayeredPane1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 51, -1));

        jLabel13.setText("Cận Nghèo TT");
        jLayeredPane1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));

        txttinh.setEditable(false);
        txttinh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txttinh.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jLayeredPane1.add(txttinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 187, -1));

        lbhuyen.setText("Huyện");
        jLayeredPane1.add(lbhuyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 51, -1));

        txtxa.setEditable(false);
        txtxa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtxa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jLayeredPane1.add(txtxa, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 187, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Địa bàn quản lý");
        jLayeredPane1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        txthuyen.setEditable(false);
        txthuyen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txthuyen.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jLayeredPane1.add(txthuyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 187, -1));

        jLabel11.setText("Nghèo TT");
        jLayeredPane1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 275, -1, -1));

        jLabel5.setText("Quyền chỉnh sửa");
        jLayeredPane1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, 20));

        add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, 340));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbttrangthai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lbhuyen;
    private javax.swing.JLabel lbxa;
    private javax.swing.JTextField txtcanngheont;
    private javax.swing.JTextField txtcanngheott;
    private javax.swing.JTextField txtcap;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txthuyen;
    private javax.swing.JTextField txtnamngheo;
    private javax.swing.JTextField txtngheott;
    private javax.swing.JTextField txtnheont;
    private javax.swing.JTextField txttinh;
    private javax.swing.JTextField txtxa;
    // End of variables declaration//GEN-END:variables
}
