/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Control.DKCanBo;
import Entity.CanBo;
import Entity.DiaBan;
import Entity.HeThong;

/**
 *
 * @author thong
 */
public class PnThongTinHeThong extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    private static CanBo userInfo;
    public PnThongTinHeThong(CanBo userInfo) {
        this.userInfo = userInfo;
        initComponents();
        txthoten.setText(userInfo.getHoTen());
        txtcap.setText((userInfo.getCapQL()==1)?"Tỉnh":(userInfo.getCapQL() == 2)? "Huyện" : "Xã");
        DiaBan db = DKCanBo.layDiaBan(userInfo.getCapQL(), userInfo.getDiaBanQL());
        switch (userInfo.getCapQL()) {
            case 1:
                lbhuyen.setVisible(false);
                txthuyen.setVisible(false);
                lbxa.setVisible(false);
                txtxa.setVisible(false);
                txttinh.setText(db.getTinh());
                break;
            case 2:
                lbxa.setVisible(false);
                txtxa.setVisible(false);
                txttinh.setText(db.getTinh());
                txthuyen.setText(db.getHuyen());
                break;
            default:
                txttinh.setText(db.getTinh());
                txthuyen.setText(db.getHuyen());
                txtxa.setText(db.getXa());
        }
        
        txtngheott.setText(""+HeThong.ngheoTT);
        txtnheont.setText(""+HeThong.ngheoNT);
        txtcanngheont.setText(""+HeThong.canNgheoNT);
        txtcanngheott.setText(""+HeThong.canNgheoTT);
        txtnamngheo.setText(""+HeThong.namNgheo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbxa = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtcap = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txthuyen = new javax.swing.JTextField();
        txtxa = new javax.swing.JTextField();
        lbhuyen = new javax.swing.JLabel();
        txttinh = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtcanngheont = new javax.swing.JTextField();
        txtcanngheott = new javax.swing.JTextField();
        txtnheont = new javax.swing.JTextField();
        txtngheott = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        txtnamngheo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txthoten = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(900, 600));

        jLabel11.setText("Nghèo TT");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Địa bàn quản lý");

        jLabel10.setText("Nghèo NT");

        lbxa.setText("Xã");

        jLabel13.setText("Cận Nghèo TT");

        jLabel12.setText("Cận nghèo NT");

        jLabel3.setText("Cấp quản lý");

        txtcap.setEditable(false);
        txtcap.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtcap.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel2.setText("Họ tên");

        txthuyen.setEditable(false);
        txthuyen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txthuyen.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtxa.setEditable(false);
        txtxa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtxa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lbhuyen.setText("Huyện");

        txttinh.setEditable(false);
        txttinh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txttinh.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel7.setText("Tỉnh");

        txtcanngheont.setEditable(false);
        txtcanngheont.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtcanngheont.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtcanngheott.setEditable(false);
        txtcanngheott.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtcanngheott.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtnheont.setEditable(false);
        txtnheont.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtnheont.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtngheott.setEditable(false);
        txtngheott.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtngheott.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jCheckBox1.setText("Quyền chỉnh sửa");
        jCheckBox1.setEnabled(false);

        txtnamngheo.setEditable(false);
        txtnamngheo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtnamngheo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel9.setText("Năm nghèo");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Thông tin hệ thống");

        txthoten.setEditable(false);
        txthoten.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txthoten.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Thông tin người dùng");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jCheckBox1)
                                            .addComponent(txthoten)
                                            .addComponent(txtcap, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel10))
                                        .addGap(114, 114, 114)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtnheont, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtngheott, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbhuyen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbxa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txthuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtxa, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttinh, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnamngheo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcanngheott, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcanngheont, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txthoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(txttinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtcap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbhuyen)
                    .addComponent(txthuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbxa)
                    .addComponent(jCheckBox1)
                    .addComponent(txtxa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(jLabel8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnamngheo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtnheont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(txtcanngheont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtngheott, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)
                                .addComponent(txtcanngheott, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(237, 237, 237))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbhuyen;
    private javax.swing.JLabel lbxa;
    private javax.swing.JTextField txtcanngheont;
    private javax.swing.JTextField txtcanngheott;
    private javax.swing.JTextField txtcap;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txthuyen;
    private javax.swing.JTextField txtnamngheo;
    private javax.swing.JTextField txtngheott;
    private javax.swing.JTextField txtnheont;
    private javax.swing.JTextField txttinh;
    private javax.swing.JTextField txtxa;
    // End of variables declaration//GEN-END:variables
}
